---
driver:
  name: proxy
  host: localhost
  reset_command: "exit 0"
  port: 5985
  username: <%= ENV["machine_user"] %>
  password: <%= ENV["machine_pass"] %>

transport:
  name: winrm
  elevated: true

provisioner:
  name: nodes
  deprecations_as_errors: true
  product_name: chef
  channel: stable
  version: 15

platforms:
  - name: windows-2012R2

verifier:
  name: inspec

suites:
  - name: dns
    run_list:
      - recipe[powershell::powershell5]
      - recipe[test::dns]
  - name: client
    run_list:
      - recipe[test::client]
